spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: 1234
    url: jdbc:postgresql://postgres:5432/springRestApp

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
